<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/2
 * Time: 11:58
 */
namespace app\controllers;
use yii\rest\ActiveController;
use yii\web\Response;

class TokenController extends ActiveController
{
   public $modelClass='app\m\Clients';
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        // 指定允许其他域名访问
        header('Access-Control-Allow-Origin:*');
        // 响应类型
        header('Access-Control-Allow-Methods:GET,POST');
        header('Access-Control-Allow-Headers:x-requested-with,content-type');
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }
    function actions()
    {
        return [
            'index' => [
                'class' => 'app\myactions\TokenAction',
                'modelClass' => $this->modelClass,
             ]
            ];
    }


}