<?php
namespace app\controllers;

use app\m\ModelFactory;
use app\m\Uploader;
use Qiniu\QiniuUtil;
use Yii;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;

class VideoController extends ComBaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation=false;
    }

    /*function actionUploadpic()
    {
        $result=new \stdClass();
        $result->name="";
        $result->status=0;
        $result->url="";
        $model = new Uploader();

        if (Yii::$app->request->isPost) {

            $model->imageFile = UploadedFile::getInstance($model, 'file');
            $getUploadResult=$model->upload();
            if ($getUploadResult) {
                // 文件上传成功
                $result->name=$getUploadResult;
                $result->url="http://localhost:9090/images/videos/".$getUploadResult."."
                    .$model->imageFile->extension;//真实的可以访问的图片的http地址
                $result->status=1;

            }
        }


        return json_encode($result);
    }*/

    function actionSubmitvideo()
    {

        if(Yii::$app->request->isPost)
        {


            //在这里我们还需要做一步 判断, 譬如必要的字段是否填写
            //请大家课后自行完成，不要前台验证完了就算验证完了。

            try
            {
                $model=ModelFactory::loadModel("videos");//主表

                $model->v_title=Yii::$app->request->getBodyParam("v_title");//视频标题

                $model->v_class=intval(Yii::$app->request->getBodyParam("v_class"));//视频类别
                $model->v_intr=Yii::$app->request->getBodyParam("v_intr");

                $model->v_pic=Yii::$app->request->getBodyParam("v_pic")["id"]; //注意v_pic 在前台也是一个子对象
                $model->v_money=intval(Yii::$app->request->getBodyParam("v_money"));//价格
                $model->v_file=Yii::$app->request->getBodyParam("v_videokey");

                $model->v_tags=implode(",",Yii::$app->request->getBodyParam("v_tags"));//前台标签传过来是一个数组。我们把它组合成 逗号分隔的内容
                if($model->save())
                {
                    //自定义一个返回 格式
                    $result=new \stdClass();
                    $result->status="success";
                    $result->id=$model->v_id;
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;  //设置当前 content-type为application/json
                    return  $result;
                }
            }
            catch(Exception $ex)
            {

                //自定义一个错误返回 格式
                $result=new \stdClass();
                $result->status="error";
                $result->msg=$ex->getMessage();
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;  //设置当前 content-type为application/json
                return  $result;
            }

        }


    }

    function actionUptoken() //返回 uptoken
    {
        $userid=0;//默认是0，代表超级管理员
        $util=new QiniuUtil();
        $ret=$util->getUploadToken($userid);
        return json_encode($ret);
    }

    function actionUploadpic()
    {
        $model = new Uploader();

        if (Yii::$app->request->isPost) {

            $model->imageFile = UploadedFile::getInstance($model, 'file');

            return   $model->upload();
        }
        return "";
    }
    function actionImgcallback() //图片上传回调
    {

        //七牛Post我们这个地址了
        if(Yii::$app->request->isPost)
        {

            $model=ModelFactory::loadModel("videos_img");//取出图片表model
            $vi=$model::find()->where(["img_name"=>Yii::$app->request->post("key")])->one();
            if($vi)
            {
                $vi->isuploaded=1;
                $vi->save();

                $result=new \stdClass();
                $result->response="success";
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;  //设置当前 content-type为application/json
                return  $result;
            }

        }

    }
}